### ISSUE TITLE
print statistics

### ISSUE THREAD

**Issue by jonorthwash** [apertium/lexd#4]
It would be good to know
- Number of entries in LEXICONs;
- less importantly, number of patterns.

**Comment by nlhowell** [comment]
@jonorthwash, does `lexd -x` do what you want? Can we close this?

**Comment by mr-martian** [comment]
there has been a further request for an option to print number of entries per lexicon.

**Comment by jonorthwash** [comment]
> there has been a further request for an option to print number of entries per lexicon.

This is actually part of what I meant by "Number of entries in LEXICONs;"
